[symlinks]
"btop/btop.conf" = "/home/ayimany/.config/btop/btop.conf"
"darkman/config/config.yaml" = "/home/ayimany/.config/darkman/config.yaml"
"darkman/dark/both.sh" = "/home/ayimany/.local/share/dark-mode.d/both.sh"
"darkman/dark/desktop-notification.sh" = "/home/ayimany/.local/share/dark-mode.d/desktop-notification.sh"
"darkman/light/both.sh" = "/home/ayimany/.local/share/light-mode.d/both.sh"
"darkman/light/desktop-notification.sh" = "/home/ayimany/.local/share/light-mode.d/desktop-notification.sh"
"fish/config.fish" = "/home/ayimany/.config/fish/config.fish"
"fish/fish_variables" = "/home/ayimany/.config/fish/fish_variables"
"fish/functions/fish_greeting.fish" = "/home/ayimany/.config/fish/functions/fish_greeting.fish"
"fish/scripts/shell-is-fish.sh" = "/home/ayimany/.config/fish/scripts/shell-is-fish.sh"
"fontconfig/fonts.conf" = "/home/ayimany/.config/fontconfig/fonts.conf"
"ghostty/config" = "/home/ayimany/.config/ghostty/config"
"glow/glow.yml" = "/home/ayimany/.config/glow/glow.yml"
"hyprland/application-style.conf" = "/home/ayimany/.config/hypr/application-style.conf"
"hyprland/hypridle.conf" = "/home/ayimany/.config/hypr/hypridle.conf"
"hyprland/hyprland.conf" = "/home/ayimany/.config/hypr/hyprland.conf"
"hyprland/hyprlock.conf" = "/home/ayimany/.config/hypr/hyprlock.conf"
"hyprland/hyprpaper.conf" = "/home/ayimany/.config/hypr/hyprpaper.conf"
"hyprland/hyprsunset.conf" = "/home/ayimany/.config/hypr/hyprsunset.conf"
"hyprland/theme/latte.conf" = "/home/ayimany/.config/hypr/theme/latte.conf"
"hyprland/theme/mocha.conf" = "/home/ayimany/.config/hypr/theme/mocha.conf"
"hyprland/theme/update-theme.sh" = "/home/ayimany/.config/hypr/theme/update-theme.sh"
"mako/config" = "/home/ayimany/.config/mako/config"
"mako/theme/:w" = "/home/ayimany/.config/mako/theme/:w"
"mako/theme/latte.mkt" = "/home/ayimany/.config/mako/theme/latte.mkt"
"mako/theme/mocha.mkt" = "/home/ayimany/.config/mako/theme/mocha.mkt"
"mako/theme/update-theme.sh" = "/home/ayimany/.config/mako/theme/update-theme.sh"
"python/pythonrc" = "/home/ayimany/.config/python/pythonrc"
"rofi/config.rasi" = "/home/ayimany/.config/rofi/config.rasi"
"rofi/theme/latte.rasi" = "/home/ayimany/.config/rofi/theme/latte.rasi"
"rofi/theme/mocha.rasi" = "/home/ayimany/.config/rofi/theme/mocha.rasi"
"rofi/theme/update-theme.sh" = "/home/ayimany/.config/rofi/theme/update-theme.sh"
"starship/starship.toml" = "/home/ayimany/.config/starship/starship.toml"
"uwsm/env" = "/home/ayimany/.config/uwsm/env"
"uwsm/env-hyprland" = "/home/ayimany/.config/uwsm/env-hyprland"
"waybar/config" = "/home/ayimany/.config/waybar/config"
"waybar/config.json" = "/home/ayimany/.config/waybar/config.json"
"waybar/style.css" = "/home/ayimany/.config/waybar/style.css"
"waybar/theme/latte.css" = "/home/ayimany/.config/waybar/theme/latte.css"
"waybar/theme/mocha.css" = "/home/ayimany/.config/waybar/theme/mocha.css"
"waybar/theme/update-theme.sh" = "/home/ayimany/.config/waybar/theme/update-theme.sh"
"xdg-desktop-portal/hyprland-portals.conf" = "/home/ayimany/.config/xdg-desktop-portal/hyprland-portals.conf"
"zathura/zathurarc" = "/home/ayimany/.config/zathura/zathurarc"

[templates]
